### PR TITLE
WMS ID: 11408

### PR DESCRIPTION
**Pull request by KellyDSmith-orcl**
# Add here your WMS ID: 11408

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [X] All filenames are lower case (including folders, images, files, etc.)
- [X] Filenames are descriptive
- [ X] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [X] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@KellyDSmith-orcl - Please check and update all the files/folder titles lowercase
image

**Comment by KellyDSmith-orcl** [comment]
I did that before the pull request, but I am not sure why it didn't sync.  Is there a method to make sure there is a sync?
Screenshot 2023-08-03 at 7 10 15 AM

**Comment by ZRTalke** [comment]
Hi @KellyDSmith-orcl 

If you update your workshop and go through the steps of creating a pull request it will update your current pull request. From there you can review the Files changed section of your pull request to make sure the updates are properly reflected

**Comment by KellyDSmith-orcl** [comment]
The case problem is resolved.

**Review by ramumg — CHANGES_REQUESTED** [review]
Hi @KellyDSmith-orcl, 

- please check the indentation for for config-tenancy.md
- For notes please use the notes syntax highlighted in the QA document 
image
- Please double-check your help contact for the desktop manifest since it doesn't match the other manifests, and it doesn't look like a valid email. 
image


Thank you, 
Ramu

**Comment by KellyDSmith-orcl** [comment]
@ramumg - fixed the two issues above

**Review by ramumg — APPROVED** [review]

**Pull request merged**
