### PR TITLE
WMD ID 11348 - Publishing "Zero Downtime Migration: Physical Online Migration with Direct Data Transfer to Co-Managed Databases in OCI"

### PR DESCRIPTION
**Pull request by aputhenc**
# WMD ID 11348

Please approve PR.

### CODE REVIEW

**Review by ZRTalke — CHANGES_REQUESTED** [review]
Hi @aputhenc 

Please remove the changes for the two workshops that aren't Zero Downtime Migration: Physical Online Migration with Direct Data Transfer to Co-Managed Databases in OCI.

- If you need to make changes to those workshops, you may submit individual pull requests for each of them with their WMS ID included

To be in compliance with the Self QA Checklist please make the following additional updates:

- Steps should be indented under tasks
- for the file name mig_eval_final the _ character cannot be used. You can however change it to mig-eval-final
- Please upload a screenshot of your lint checker to the Self QA Checklist

Other than those updates the workshop looks good!

**Comment by anooshapilli** [comment]
@aputhenc Could you update the WMS IDs of the workshops folders that had changes other than ID 11348

**Comment by aputhenc** [comment]
Hi @anooshapilli @ZRTalke ,

Thank you for reviewing the PR.

I have made the requested changes for the WMS ID : 11348, However I am still in the process of updating one of my workshops in the same repository and it is taking some more time.

Please advise is it better to separate each workshop into separate forks so that the issue of updating multiple workshops at the same time can be resolved.

Thank you

**Comment by ZRTalke** [comment]
Hi @aputhenc 

Yes. If you separate them I can approve the one for 11348 while you work on the other workshops

**Comment by anooshapilli** [comment]
@aputhenc   - Could you confirm if the requested changes are made to this PR?

**Comment by aputhenc** [comment]
@anooshapilli , I have reverted the changes to WMS ID 11320 since they need more time. All other changes for WMS ID 11344 and 11348 are good to go.

I have included WMS ID 11320 also in the subject since I see changes reverted will go as another commit.

**Review by ramumg — CHANGES_REQUESTED** [review]
Hi @aputhenc,

It looks like in some md files the indentation is not consistent.  Your file should look like this: 
image

After the indentation is fixed we can go ahead and merge the PR. Let me know if you have any questions.

Thank you, 
Ramu

**Comment by aputhenc** [comment]
Hi @ramumg ,

Please note that I had worked only the indentation for the past couple of days.

I have again changed the indentation for source-db-provision.md, Please verify it so that I can replicate the same to other .md files.

To be frank, the actual livelab page for source-db-provision doesn't look good now but then I am not sure whether this is the standard for indentation.

Thanks
Amalraj

**Comment by ramumg** [comment]
Hi @aputhenc let's discuss in slack.

**Review by ramumg — APPROVED** [review]

**Review by ZRTalke — APPROVED** [review]

**Pull request merged**
